# To Do

- Get information about how w2v is calculated

In [34]:
import pandas as pd
import numpy as np
from scipy import spatial
import pickle
from sklearn.cluster import KMeans

In [3]:
products = pd.read_csv('~/work/products.csv')

In [4]:
### Reading in Instacart Feature Vec

df_instacart_product_vectors = pd.read_csv("~/work/instacart_feature_vec.csv", header=None)

df_instacart_product_vectors.head()

df_instacart_product_vectors = df_instacart_product_vectors.drop(101, axis=1)

df_instacart_product_vectors = df_instacart_product_vectors.sort_values(0)

df_instacart_product_vectors = df_instacart_product_vectors.drop(0, axis=1)

np_instacart_product_vectors = df_instacart_product_vectors.to_numpy()

np_instacart_product_vectors = np.insert(np_instacart_product_vectors, 0, np.zeros(100), 0)

print (np_instacart_product_vectors.shape)

# only if we're using negative sampling
# np_instacart_product_vectors = np.take(np_instacart_product_vectors, w2v_indices, axis=0)

# df_train.product_id.nunique()
# del df_instacart_product_vectors
# gc.collect()
# df_instacart_product_vectors = pd.DataFrame()

(49688, 100)

In [21]:
with open('np_instacart_product_vectors.pkl', 'wb') as f:
    pickle.dump(np_instacart_product_vectors, f)

In [5]:
products['features'] = pd.Series(np_instacart_product_vectors.tolist())

In [18]:
products[products.product_name.str.contains("Burger")]

,product_id,product_name,aisle_id,department_id,features
22,23,Organic Turkey Burgers,49,12,"[0.0675775144822891, -0.0599452063735397, 0.01..."
170,171,Steakhouse Onion Burger with Garlic Seasoning,5,13,"[-0.0194565389208161, -0.0046446463414685, -0...."
1119,1120,All American Flame Grilled Veggie Burgers,42,1,"[0.0293236503102702, 0.0171298874076949, -0.01..."
1476,1477,Wild Mushroom Cauliflower Hempseed Burgers,42,1,"[-0.0252100263048436, -0.1413423408576508, -0...."
1869,1870,Chipotle Black Bean Burger,34,1,"[0.1578014923510028, 0.0093311321926252, 0.102..."
...,...,...,...,...,...
48015,48016,Garden Vegetable Tempeh Burger,7,12,"[0.1330763668120287, -0.0477503947415554, 0.06..."
48747,48748,Burger Artichoke Tandoori,38,1,"[0.0944562026523818, -0.062596170602095, 0.008..."
48868,48869,Barbecue Veggie Burgers,42,1,"[0.0961062563326119, -0.0305633713519169, 0.06..."
49228,49229,Mushroom Rice Burger Patties,42,1,"[-0.0465431563072303, -0.1461236442593102, -0...."
49284,49285,Turkey Burgers,34,1,"[0.0674435719888884, -0.0924056316335367, -0.0..."

In [7]:
vector_list = np_instacart_product_vectors.tolist()

In [19]:
#vector_list = products.features.tolist()
index = 1869
study_index_vector = vector_list[index]

print (products.loc[index, 'product_name'])
#mod_vector_list = vector_list[:index] + vector_list[index+1:]
# vector_list[index] = np.ones(100) * 20
tree = spatial.KDTree(vector_list)

Chipotle Black Bean Burger

In [20]:
tree.query(study_index_vector, k=20)

(array([0.        , 0.32672109, 0.36895395, 0.39070393, 0.50977487,
        0.51410909, 0.51685559, 0.53117588, 0.56090152, 0.57292672,
        0.58795255, 0.60964636, 0.60964636, 0.61934869, 0.62114791,
        0.62391009, 0.63278743, 0.63829321, 0.63893257, 0.64777776]),
 array([ 1869, 47110, 45711,  5217, 38475, 44540, 33383, 14409, 25835,
        30244, 21171, 14071, 18537, 49449, 28622, 30827, 22825, 36439,
        42930, 28376]))

In [22]:
tree_search_indices = tree.query(study_index_vector, k=20)[1]
print (tree_search_indices)
temp = products.loc[tree_search_indices]

[ 1869 47110 45711  5217 38475 44540 33383 14409 25835 30244 21171 14071
 18537 49449 28622 30827 22825 36439 42930 28376]

In [24]:
temp["Euclidean Distance"] = tree.query(study_index_vector, k=20)[0]

In [27]:
temp.rename({"product_name": "Product Name"}, axis=1, inplace=True)

In [33]:
temp[["Product Name", "Euclidean Distance"]].reset_index(drop=True)

                                         Product Name  Euclidean Distance
0                          Chipotle Black Bean Burger            0.000000
1                             Spicy Black Bean Burger            0.326721
2                        Chipotle Black Bean Crumbles            0.368954
3                           Black Bean Chipotle Vegan            0.390704
4           Black Bean Chipotle Veggie Burger Patties            0.509775
5                  Black Bean Burger Meatless Patties            0.514109
6                                  Black Bean Burgers            0.516856
7                     Spicy Black Bean Veggie Burgers            0.531176
8             Burgers Spicy Black Bean Veggie Burgers            0.560902
9                                  Black Bean Tamales            0.572927
10  Burrito, Meatless, Chik'n & Tomato Roasted Cor...            0.587953
11                                   Black Bean Salsa            0.609646
12                                  Salsa, Black Bean            0.609646
13                            Medium Black Bean Salsa            0.619349
14             Burgers, Veggie, Black Bean South West            0.621148
15                                Burger Veggie Curry            0.623910
16          Gluten-Free Chipotle BBQ Black Bean Chips            0.632787
17                                 Artisan Black Bean            0.638293
18          Medium Corn Black Bean & Red Pepper Salsa            0.638933
19                     Medium Black Bean & Corn Salsa            0.647778

In [21]:
tree_search_indices = tree.query(study_index_vector, k=20)[1]
print (tree_search_indices)
products.loc[tree_search_indices]

[ 1869 47110 45711  5217 38475 44540 33383 14409 25835 30244 21171 14071
 18537 49449 28622 30827 22825 36439 42930 28376]

,product_id,product_name,aisle_id,department_id,features
1869,1870,Chipotle Black Bean Burger,34,1,"[0.1578014923510028, 0.0093311321926252, 0.102..."
47110,47111,Spicy Black Bean Burger,42,1,"[0.0568277219330874, -0.0349266474242755, 0.12..."
45711,45712,Chipotle Black Bean Crumbles,42,1,"[0.1598032811950612, -0.0198865965857861, 0.05..."
5217,5218,Black Bean Chipotle Vegan,42,1,"[0.1522012224648109, -0.0063668010541409, 0.06..."
38475,38476,Black Bean Chipotle Veggie Burger Patties,42,1,"[0.1495560906861876, -0.0653628628980902, -0.0..."
44540,44541,Black Bean Burger Meatless Patties,14,20,"[0.0819372201725786, -0.0502292054228564, 0.04..."
33383,33384,Black Bean Burgers,42,1,"[0.0417554696391129, -0.0443138110582929, 0.10..."
14409,14410,Spicy Black Bean Veggie Burgers,42,1,"[0.0533118865758847, -0.0531725889093719, 0.09..."
25835,25836,Burgers Spicy Black Bean Veggie Burgers,42,1,"[0.0630993558954095, -0.0460828416898468, 0.07..."
30244,30245,Black Bean Tamales,13,20,"[0.0698034003136903, -0.0581650661193766, 0.06..."
21171,21172,"Burrito, Meatless, Chik'n & Tomato Roasted Cor...",42,1,"[0.169705382167437, -0.0920261673785179, 0.014..."
14071,14072,Black Bean Salsa,51,13,"[0.0730163061714214, -0.0050754804378394, 0.18..."
18537,18538,"Salsa, Black Bean",51,13,"[0.0730163061714214, -0.0050754804378394, 0.18..."
49449,49450,Medium Black Bean Salsa,51,13,"[0.0862107872081416, -0.0077499304591063, 0.17..."
28622,28623,"Burgers, Veggie, Black Bean South West",42,1,"[0.1127474874839504, -0.054264621116811, 0.151..."
30827,30828,Burger Veggie Curry,38,1,"[0.1193641190322612, -0.0554416788941261, 0.02..."
22825,22826,Gluten-Free Chipotle BBQ Black Bean Chips,107,19,"[0.0795715783570252, -0.0291417835497815, 0.00..."
36439,36440,Artisan Black Bean,107,19,"[-0.0343278389066385, -0.0283116962967112, 0.1..."
42930,42931,Medium Corn Black Bean & Red Pepper Salsa,51,13,"[0.086176397110838, 0.0172307939559046, 0.1749..."
28376,28377,Medium Black Bean & Corn Salsa,51,13,"[0.0721725125322426, 0.0065290310300669, 0.190..."

## Testing out ANNOY

In [23]:
!pip install --user annoy

Collecting annoy
  Downloading annoy-1.17.0.tar.gz (646 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 646.2/646.2 KB 10.9 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: annoy
  Building wheel for annoy (setup.py) ... done
  Created wheel for annoy: filename=annoy-1.17.0-cp38-cp38-linux_x86_64.whl size=578700 sha256=6292e5da3cc0c2da49f93ab74e438af263b427d954464702d129527a33db0cc6
  Stored in directory: /home/jovyan/.cache/pip/wheels/77/01/de/4421524f9997a25dfa7291121565d12ef514154945e80e907a
Successfully built annoy
Installing collected packages: annoy
Successfully installed annoy-1.17.0
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/opt/conda/bin/python3.8 -m pip install --upgrade pip' command.

In [24]:
from annoy import AnnoyIndex

In [25]:
t = AnnoyIndex(100, 'angular')

In [26]:
for i, v in enumerate(np_instacart_product_vectors):
    t.add_item(i, v)

# Clusters for Instacart Dataset

In [37]:
kmeans = KMeans(n_clusters=10000)
kmeans.fit(np_instacart_product_vectors)
len(kmeans.labels_)
labels_to_productid_dict = dict(zip(range(len(kmeans.labels_)), kmeans.labels_))

In [38]:
with open('instacart_productid_to_clusterlabel_dict.pkl', 'wb') as f:
    pickle.dump(labels_to_productid_dict, f)

In [40]:
products

,product_id,product_name,aisle_id,department_id,features
0,1,Chocolate Sandwich Cookies,61,19,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,2,All-Seasons Salt,104,13,"[-0.1886489229916697, 0.0543145344975171, -0.0..."
2,3,Robust Golden Unsweetened Oolong Tea,94,7,"[0.1334283426670505, -0.0902027653847868, 0.16..."
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,"[-0.0011966451791447, -0.1739609565096758, -0...."
4,5,Green Chile Anytime Sauce,5,13,"[0.0764108849932647, -0.1362777847449642, -0.1..."
...,...,...,...,...,...
49683,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,"[0.0134300750235264, -0.0848616948163522, -0.0..."
49684,49685,En Croute Roast Hazelnut Cranberry,42,1,"[0.1162948097134905, -0.0611463030567391, -0.0..."
49685,49686,Artisan Baguette,112,3,"[-0.1906933951120195, 0.0511844864849408, -0.0..."
49686,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,"[-0.1142655518529637, -0.0777084066656007, 0.1..."
49687,49688,Fresh Foaming Cleanser,73,11,"[0.0732283711346606, -0.2007851361261685, 0.09..."

In [44]:
products["cluster_label"] = pd.Series(labels_to_productid_dict.values())

In [49]:
products

,product_id,product_name,aisle_id,department_id,features,cluster_label
0,1,Chocolate Sandwich Cookies,61,19,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",23
1,2,All-Seasons Salt,104,13,"[-0.1886489229916697, 0.0543145344975171, -0.0...",825
2,3,Robust Golden Unsweetened Oolong Tea,94,7,"[0.1334283426670505, -0.0902027653847868, 0.16...",1892
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,"[-0.0011966451791447, -0.1739609565096758, -0....",8525
4,5,Green Chile Anytime Sauce,5,13,"[0.0764108849932647, -0.1362777847449642, -0.1...",2564
...,...,...,...,...,...,...
49683,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,"[0.0134300750235264, -0.0848616948163522, -0.0...",319
49684,49685,En Croute Roast Hazelnut Cranberry,42,1,"[0.1162948097134905, -0.0611463030567391, -0.0...",8541
49685,49686,Artisan Baguette,112,3,"[-0.1906933951120195, 0.0511844864849408, -0.0...",3163
49686,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,"[-0.1142655518529637, -0.0777084066656007, 0.1...",9798
49687,49688,Fresh Foaming Cleanser,73,11,"[0.0732283711346606, -0.2007851361261685, 0.09...",4068

In [50]:
products[products.cluster_label == 2564]

,product_id,product_name,aisle_id,department_id,features,cluster_label
4,5,Green Chile Anytime Sauce,5,13,"[0.0764108849932647, -0.1362777847449642, -0.1...",2564
3251,3252,Medium Green Chile Enchilada Sauce,30,6,"[0.1168406868669985, -0.1367256876374023, -0.0...",2564
9363,9364,Mild Green Chile Enchilada Sauce,30,6,"[0.1014727398028165, -0.13354394559677, -0.054...",2564
20912,20913,Organic Enchilada Green Sauce Mild,30,6,"[0.1058727901144524, -0.1036915841301048, 0.02...",2564
28707,28708,Picante Hot Green Chile Enchilada Sauce,30,6,"[0.0962004900813194, -0.1250582948468301, -0.0...",2564
29918,29919,Roasted Green Chile Tamales,30,6,"[0.134540631283568, -0.0549583009389711, -0.05...",2564
31258,31259,Mild Enchilada Green Chile Sauce,30,6,"[0.1014727398028165, -0.13354394559677, -0.054...",2564
36262,36263,Green Chile Medium Enchilada Sauce,30,6,"[0.1168406868669985, -0.1367256876374023, -0.0...",2564
36646,36647,Green Chile Zucchini,42,1,"[0.1338335740952893, -0.027444770174345, -0.04...",2564
41833,41834,Green Chile Enchilada Sauce,30,6,"[0.1078857839053975, -0.1407432641634827, -0.0...",2564